### ISSUE TITLE
Angular data binding not working correctly from fresh install.

### ISSUE THREAD

**Issue by goleary** [flrent/chrome-extension-angular-base#1]
I downloaded a zip of the repo, and did a build using grunt.  When I load the unpacked extension and open the popup, this is what I see:
![image](https://cloud.githubusercontent.com/assets/16123225/13153148/6d047264-d627-11e5-9dce-96b7c2d236b3.png)

**Comment by flrent** [comment]
hi @golear91, just tried again and it works for me. Did you run `bower install` after `npm install` by any chance ?

**Comment by goleary** [comment]
Your intuition was correct.  Thanks!
